Repository canonical/paas-app-charmer, pull requests merged in 2024-08, with the labels that each got.

#32 Refactor to adapt paas-app-charmer for new frameworks
  .github/workflows/integration_test.yaml
  .trivyignore
  examples/django/charm/charmcraft.yaml
  examples/flask/charmcraft.yaml
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/secret_storage.py
  paas_app_charmer/_gunicorn/webserver.py
  paas_app_charmer/_gunicorn/workload_config.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/app.py
  paas_app_charmer/charm.py
  paas_app_charmer/charm_state.py
  paas_app_charmer/charm_utils.py
  paas_app_charmer/django/__init__.py
  paas_app_charmer/django/charm.py
  paas_app_charmer/flask/__init__.py
  paas_app_charmer/flask/charm.py
  paas_app_charmer/observability.py
  paas_app_charmer/secret_storage.py
  tests/conftest.py
  tests/integration/conftest.py
  tests/integration/django/conftest.py
  tests/integration/django/test_django_integrations.py
  tests/integration/flask/conftest.py
  tests/unit/django/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_database_migration.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_webserver.py
Labels: complex

#9 Docs
  README.md
Labels: documentation, trivial

#35 Add FastAPI support to paas-app-charmer
  .github/workflows/integration_test.yaml
  .woke.yaml
  examples/fastapi/alembic.ini
  examples/fastapi/alembic/env.py
  examples/fastapi/alembic/versions/eca6177bd16a_initial_migration.py
  examples/fastapi/app.py
  examples/fastapi/charm/charmcraft.yaml
  examples/fastapi/charm/lib/charms/data_platform_libs/v0/data_interfaces.py
  examples/fastapi/charm/lib/charms/data_platform_libs/v0/s3.py
  examples/fastapi/charm/lib/charms/grafana_k8s/v0/grafana_dashboard.py
  examples/fastapi/charm/lib/charms/loki_k8s/v0/loki_push_api.py
  examples/fastapi/charm/lib/charms/observability_libs/v0/juju_topology.py
  examples/fastapi/charm/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  examples/fastapi/charm/lib/charms/redis_k8s/v0/redis.py
  examples/fastapi/charm/lib/charms/saml_integrator/v0/saml.py
  examples/fastapi/charm/lib/charms/traefik_k8s/v2/ingress.py
  examples/fastapi/charm/requirements.txt
  examples/fastapi/charm/src/charm.py
  examples/fastapi/migrate.sh
  examples/fastapi/requirements.txt
  examples/fastapi/rockcraft.yaml
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/app.py
  paas_app_charmer/fastapi/__init__.py
  paas_app_charmer/fastapi/charm.py
  pyproject.toml
  tests/conftest.py
  tests/integration/fastapi/__init__.py
  tests/integration/fastapi/conftest.py
  tests/integration/fastapi/test_fastapi.py
  tests/unit/fastapi/__init__.py
  tests/unit/fastapi/conftest.py
  tests/unit/fastapi/constants.py
  tests/unit/fastapi/test_charm.py
Labels: complex

#38 Fix wrong prefix for secret-key and do not allow extra fields in framework configs.
  examples/fastapi/charm/charmcraft.yaml
  paas_app_charmer/fastapi/charm.py
  paas_app_charmer/go/charm.py
  tests/unit/fastapi/test_charm.py
  tests/unit/go/test_app.py
Labels: bug, trivial
