Repository canonical/paas-app-charmer, pull requests merged in 2024-09, with the labels that each got.

#42 Require a database for Django to start
  paas_app_charmer/django/charm.py
  tests/unit/django/conftest.py
  tests/unit/django/test_charm.py
Labels: bug, trivial

#45 Reenable self hosted runners
  .github/workflows/test.yaml
Labels: trivial

#47 Use rockcraft from latest/edge channel for integration tests.
  .github/workflows/integration_test.yaml
Labels: trivial

#44 Background tasks
  .github/workflows/integration_test.yaml
  examples/flask/test_rock/app.py
  examples/flask/test_rock/requirements.txt
  examples/flask/test_rock/rockcraft.yaml
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/workload_config.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/app.py
  paas_app_charmer/charm.py
  paas_app_charmer/charm_state.py
  paas_app_charmer/database_migration.py
  paas_app_charmer/fastapi/charm.py
  paas_app_charmer/go/charm.py
  paas_app_charmer/observability.py
  tests/integration/conftest.py
  tests/integration/flask/test_workers.py
  tests/unit/django/test_charm.py
  tests/unit/fastapi/test_charm.py
  tests/unit/flask/constants.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_database_migration.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_webserver.py
  tests/unit/flask/test_workers.py
  tests/unit/go/test_app.py
Labels: complex

#49 Improve test resilience
  tests/integration/flask/conftest.py
Labels: trivial

#46 Add secret configurations
  examples/django/charm/charmcraft.yaml
  examples/fastapi/charm/charmcraft.yaml
  examples/flask/charmcraft.yaml
  examples/go/charm/charmcraft.yaml
  paas_app_charmer/app.py
  paas_app_charmer/charm.py
  paas_app_charmer/charm_state.py
  paas_app_charmer/django/charm.py
  paas_app_charmer/fastapi/charm.py
  paas_app_charmer/flask/charm.py
  paas_app_charmer/framework.py
  paas_app_charmer/go/charm.py
  paas_app_charmer/utils.py
  tests/integration/flask/conftest.py
  tests/integration/flask/test_charm.py
  tests/unit/django/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_flask_app.py
Labels: trivial
