Repository canonical/paas-app-charmer, pull requests merged in 2024-06, with the labels that each got.

#17 Release version 1.0.2
  pyproject.toml
Labels: trivial, urgent

#18 Refactor for integrations
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/charm_state.py
  paas_app_charmer/_gunicorn/charm_utils.py
  paas_app_charmer/_gunicorn/observability.py
  paas_app_charmer/_gunicorn/webserver.py
  paas_app_charmer/_gunicorn/workload_config.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/databases.py
  paas_app_charmer/django/charm.py
  pyproject.toml
  tests/unit/django/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_database_migration.py
  tests/unit/flask/test_databases.py
  tests/unit/flask/test_flask_app.py
  tests/unit/flask/test_webserver.py
Labels: complex

#20 Tell users how to download any missing libraries
  paas_app_charmer/__init__.py
  paas_app_charmer/exceptions.py
Labels: trivial

#19 S3 Integration for paas-app-charmer
  .github/workflows/integration_test.yaml
  examples/flask/charmcraft.yaml
  examples/flask/lib/charms/data_platform_libs/v0/s3.py
  examples/flask/test_rock/app.py
  examples/flask/test_rock/requirements.txt
  localstack-installation.sh
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/charm_state.py
  paas_app_charmer/_gunicorn/charm_utils.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/django/charm.py
  paas_app_charmer/flask/charm.py
  tests/conftest.py
  tests/integration/flask/conftest.py
  tests/integration/flask/test_s3.py
  tests/unit/django/test_charm.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tests/unit/flask/test_flask_app.py
  tox.ini
Labels: complex

#21 Implement Saml integration
  .github/workflows/integration_test.yaml
  examples/flask/charmcraft.yaml
  examples/flask/lib/charms/saml_integrator/v0/saml.py
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/charm_state.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/django/charm.py
  paas_app_charmer/flask/charm.py
  paas_app_charmer/utils.py
  tests/integration/flask/test_integrations.py
  tests/unit/flask/constants.py
  tests/unit/flask/test_charm.py
  tests/unit/flask/test_charm_state.py
  tox.ini
Labels: trivial

#23 Block on non optional integrations
  .trivyignore
  examples/django/charm/charmcraft.yaml
  examples/flask/charmcraft.yaml
  paas_app_charmer/_gunicorn/charm.py
  paas_app_charmer/_gunicorn/charm_state.py
  paas_app_charmer/_gunicorn/wsgi_app.py
  paas_app_charmer/database_migration.py
  tests/integration/django/conftest.py
  tests/integration/django/test_django.py
  tests/integration/django/test_integrations.py
  tests/unit/django/test_charm.py
  tests/unit/flask/constants.py
  tests/unit/flask/test_charm.py
Labels: trivial
